# Generated by Django 4.2.20 on 2025-05-26 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0002_studentprofile_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Card', 'Card'), ('MobileMoney', 'Mobile Money'), ('BankTransfer', 'Bank Transfer'), ('PayPal', 'PayPal')], max_length=30)),
                ('provider', models.CharField(max_length=50)),
                ('account_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
