# Generated by Django 4.2.20 on 2025-05-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
