# Generated by Django 4.2.20 on 2025-06-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_alter_feestructure_class_level_alter_invoice_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='term',
            field=models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='class_level',
            field=models.CharField(choices=[('Grade 1', 'Grade 1'), ('Grade 7', 'Grade 7'), ('Form 1', 'Form 1'), ('Form 4', 'Form 4'), ('Form 6', 'Form 6'), ('UG', 'UG'), ('Grad', 'Grad')], max_length=50),
        ),
    ]
