# Generated by Django 4.2.20 on 2025-06-04 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_studentprofile_term_alter_studentprofile_class_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='balance',
        ),
    ]
