"""
Django settings for edupay project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

from decouple import config

SECRET_KEY = config('SECRET_KEY')
DEBUG = config('DEBUG', cast=bool)


# ALLOWED_HOSTS = []
# ALLOWED_HOSTS = ['your-app-name.onrender.com']
ALLOWED_HOSTS = [
    'edupayy-railway.onrender.com',
    '127.0.0.1',
    'localhost',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_browser_reload',
    'django_tables2',
    'widget_tweaks',
    'yuzzaz',
    'billing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'edupay.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'edupay.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

USE_I18N = True
TIME_ZONE = 'Africa/Nairobi'
USE_TZ = True  # Keep this True to store times in UTC
CELERY_TIMEZONE = 'Africa/Nairobi'

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'yuzzaz.CustomUser'

from decouple import config
# settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'gftinity01@gmail.com'  # Use your Gmail address here
# EMAIL_HOST_PASSWORD = 'pjrrcldgbkeiwapb'  # Use the app password (not your Google account password)
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')  # Use the app password (not your Google account password)

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'mail.tansaf.or.tz'
# EMAIL_PORT = 465
# EMAIL_USE_SSL = True  # <-- change this
# EMAIL_USE_TLS = False  # <-- add this line
# # EMAIL_HOST_USER = 'admissions@tansaf.or.tz'
# # EMAIL_HOST_PASSWORD = '5xGTh451287#'
# from decouple import config
# EMAIL_HOST_USER = config('EMAIL_HOST_USER')
# EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
# DEFAULT_FROM_EMAIL = 'admissions@tansaf.or.tz'


# In settings.py
LOGIN_REDIRECT_URL = 'dashboard'  # This will redirect the user to the dashboard after login


import os

# Define where media files (images, uploaded files, etc.) will be stored
MEDIA_URL = '/media/'  # URL that will be used to access media files
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # Directory where media files are saved

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, "static")]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

CRISPY_TEMPLATE_PACK = 'bootstrap5'  # Use 'bootstrap5' if you're using Bootstrap 5



#stripe
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY')  # Use the app password (not your Google account password)
STRIPE_PUBLISHABLE_KEY = config('STRIPE_PUBLISHABLE_KEY')  # Use the app password (not your Google account password)
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET')

#celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
INSTALLED_APPS += ['django_celery_beat']


import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=config('DATABASE_URL'), conn_max_age=600
    )
}
