# Generated by Django 4.2.20 on 2025-05-28 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yuzzaz', '0005_notification_usernotificationstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotificationstatus',
            options={'verbose_name': 'User Notification Status', 'verbose_name_plural': 'User  Notification Statuses'},
        ),
    ]
